package com.example;


import jakarta.inject.Inject;
import jakarta.transaction.Transactional;
import jakarta.validation.Valid;
import jakarta.ws.rs.*;
import jakarta.ws.rs.core.MediaType;
import jakarta.ws.rs.core.Response;
import jakarta.ws.rs.core.UriInfo;
import jakarta.ws.rs.core.Context;
import java.util.List;

@Path("/kullanici")
@Produces(MediaType.APPLICATION_JSON)
@Consumes(MediaType.APPLICATION_JSON)
public class KullaniciResource {

    @Inject
    KullaniciRepository kullaniciRepository;

    @GET
    public List<Kullanici> getAllKullanicilar() {
        return kullaniciRepository.listAll();
    }

    @GET
    @Path("/{id}")
    public Kullanici getKullanici(@PathParam("id") Long id) {
        return kullaniciRepository.findByIdOptional(id)
                .orElseThrow(() -> new NotFoundException("Kullanıcı bulunamadı"));
    }

    @POST
    @Transactional
    public Response createKullanici(@Valid Kullanici kullanici, @Context UriInfo uriInfo) {
        // The id is generated by the database; ignore any id sent by the client.
        kullanici.setId(null);
        ensureEmailIsFree(kullanici.getEmail(), null);
        kullaniciRepository.persist(kullanici);
        return Response.created(uriInfo.getAbsolutePathBuilder().path(kullanici.getId().toString()).build())
                .entity(kullanici)
                .build();
    }

    @PUT
    @Path("/{id}")
    @Transactional
    public Kullanici updateKullanici(@PathParam("id") Long id, @Valid Kullanici kullanici) {
        Kullanici existing = kullaniciRepository.findByIdOptional(id)
                .orElseThrow(() -> new NotFoundException("Kullanıcı bulunamadı"));
        ensureEmailIsFree(kullanici.getEmail(), id);
        existing.setIsim(kullanici.getIsim());
        existing.setEmail(kullanici.getEmail());
        return existing;
    }

    @DELETE
    @Path("/{id}")
    @Transactional
    public Response deleteKullanici(@PathParam("id") Long id) {
        if (!kullaniciRepository.deleteById(id)) {
            throw new NotFoundException("Kullanıcı bulunamadı");
        }
        return Response.noContent().build();
    }

    private void ensureEmailIsFree(String email, Long ownerId) {
        kullaniciRepository.findByEmail(email)
                .filter(other -> !other.getId().equals(ownerId))
                .ifPresent(other -> {
                    throw new ClientErrorException("Bu e-posta adresi zaten kullanılıyor", Response.Status.CONFLICT);
                });
    }
}
