version: 2
updates:
  - package-ecosystem: "maven" 
    directory: "/PlayWithThreads" 
    schedule:
      interval: "weekly" 
    open-pull-requests-limit: 5 
    rebase-strategy: "auto" 
    ignore:
      - dependency-name: "org.springframework.*" 
