spring.application.name=PlayWithStreams
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.h2.console.enabled=true
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.mvc.problemdetails.enabled=true
# Upper bound for the size parameter of paged requests
spring.data.web.pageable.max-page-size=100
