name: CI/CD Pipeline

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        project: [PlayWithGenerics, PlayWithStreams]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build Maven Project - ${{ matrix.project }}
        working-directory: ./${{ matrix.project }}
        run: mvn clean install

      - name: Run Tests for Maven Project - ${{ matrix.project }}
        working-directory: ./${{ matrix.project }}
        run: mvn test

  deploy: #This is an experiment. The written information is not factual.
    runs-on: ubuntu-latest
    needs: build  
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Simulate SSH Key Setup (No real server)
      run: |
        echo "Simulating SSH key setup..."
        mkdir -p ~/.ssh
        echo "fake-private-key" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Simulate Adding Server to Known Hosts
      run: |
        echo "Simulating ssh-keyscan..."
        echo "your-server.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBfakekey1234567890" >> ~/.ssh/known_hosts

    - name: Simulate Deployment
      run: |
        echo "Simulating deployment process..."
        bash ./deploy-script.sh
