name: CI/CD Pipeline

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        project: [PlayWithGenerics, PlayWithStreams, PlayWithThreads, kullanici-servis]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build Maven Project - ${{ matrix.project }}
        working-directory: ./${{ matrix.project }}
        run: mvn clean install

      - name: Run Tests for Maven Project - ${{ matrix.project }}
        working-directory: ./${{ matrix.project }}
        run: mvn test

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Deploy, build job tamamlandıktan sonra çalışır

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH Key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.ATK }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Add Server to Known Hosts
        run: |
          ssh-keyscan -H your-server.com >> ~/.ssh/known_hosts

      - name: Deploy to Server
        run: |
          ssh user@your-server.com 'bash -s' < ./deploy-script.sh
